title: Readwise/WorkFlowy Integration
author: Zackdn
email: zackdn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Import your Readwise notes directly into Workflowy with just a click!

# social links
linkedin_username: zackdn # DO NOT include the @ character, or else the build will fail!
github_username:  zackdn # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
